### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by thogb** [TomatoesBurner/ArtFusion-AI-Hub#5]
Login page UI

**Comment by cloud9ight** [comment]
Add basic Login page
Next step: will combine sign-up with login together -- *Don't have an account? Sign up for free*

**Comment by cloud9ight** [comment]
Initial login UI design, linked to register page

**Comment by cloud9ight** [comment]
I've implemented the Google OAuth callback handling on the frontend. The callback page is located at src/app/auth/callback/page.tsx. It currently makes a POST request to /api/auth/token with the authorization code obtained from Google.

For the integration, please ensure the backend endpoint /api/auth/token is set up to exchange the authorization code for an access token and handle any errors appropriately.

Feel free to reach out if you need further details or assistance on the frontend side.
